import * as Blockly from 'blockly';
import * as ZhHans from 'blockly/msg/zh-hans';

const CUSTOM_MSG: Record<string, string> = {
  BLOCKLY_CAT_EVENT: '事件',
  BLOCKLY_CAT_MESSAGE: '消息',
  BLOCKLY_CAT_LOG: '日志',
  BLOCKLY_CAT_STORAGE: '存储',
  BLOCKLY_CAT_TEXT: '文本',
  BLOCKLY_CAT_MATH: '数学',
  BLOCKLY_CAT_LOGIC: '逻辑',
  BLOCKLY_CAT_LOOP: '循环',
  BLOCKLY_CAT_LIST: '列表',
  BLOCKLY_CAT_VARIABLE: '变量',
  BLOCKLY_CAT_FUNCTION: '函数',
  BLOCKLY_CAT_ADVANCED: '高级',
  BLOCKLY_LOG_OUTPUT: '输出 %1 日志 内容 %2',
  BLOCKLY_LOG_INFO: '输出普通日志 内容 %1',
  BLOCKLY_LOG_WARN: '输出警告日志 内容 %1',
  BLOCKLY_LOG_ERROR: '输出错误日志 内容 %1',
  BLOCKLY_LOG_DEBUG: '输出调试日志 内容 %1',
  BLOCKLY_MESSAGE_SEND_GROUP: '发送群消息 群ID %1 内容 %2',
  BLOCKLY_MESSAGE_SEND_PRIVATE: '发送私聊消息 用户ID %1 内容 %2',
  BLOCKLY_MESSAGE_REPLY: '回复消息 事件 %1 内容 %2',
  BLOCKLY_MESSAGE_GET_TYPE: '获取消息类型 事件 %1',
  BLOCKLY_MESSAGE_GET_PLAIN_TEXT: '获取纯文本内容 事件 %1',
  BLOCKLY_MESSAGE_CONTAINS_KEYWORD: '消息包含关键词 事件 %1 关键词 %2',
  BLOCKLY_MESSAGE_IS_AT_BOT: '是否 @ 机器人 事件 %1',
  BLOCKLY_MESSAGE_GET_SENDER_ID: '获取发送者ID 事件 %1',
  BLOCKLY_MESSAGE_GET_GROUP_ID: '获取群ID 事件 %1',
  BLOCKLY_MESSAGE_IS_GROUP_MESSAGE: '是否群消息 事件 %1',
  BLOCKLY_MESSAGE_IS_PRIVATE_MESSAGE: '是否私聊消息 事件 %1',
  BLOCKLY_MESSAGE_SEND_PRIVATE_RESULT: '发送私聊消息并处理结果 用户ID %1 内容 %2 成功时 %3 失败时 %4',
  BLOCKLY_MESSAGE_SEND_GROUP_RESULT: '发送群消息并处理结果 群ID %1 内容 %2 成功时 %3 失败时 %4',
  BLOCKLY_EVENT_ON_MESSAGE: '当收到消息时 执行 %1',
  BLOCKLY_EVENT_ON_NOTICE: '当收到通知时 执行 %1',
  BLOCKLY_EVENT_ON_REQUEST: '当收到请求时 执行 %1',
  BLOCKLY_EVENT_ON_INIT: '当插件初始化时 执行 %1',
  BLOCKLY_EVENT_ON_DESTROY: '当插件销毁时 执行 %1',
  BLOCKLY_EVENT_GET_CURRENT: '获取当前事件',
  BLOCKLY_STORAGE_SET: '存储 键 %1 值 %2',
  BLOCKLY_STORAGE_GET: '获取存储值 键 %1 默认值 %2',
  BLOCKLY_TEXT_CONCAT: '连接文本 %1 和 %2',
  BLOCKLY_TEXT_TEMPLATE: '文本模板 %1',
  BLOCKLY_LOGIC_IF_ELSE: '如果 %1 执行 %2 否则 %3',
  BLOCKLY_API_CALL_WITH_RESULT: '调用 API 并处理结果 名称 %1 参数1 %2 参数2 %3 成功时 %4 失败时 %5',
  BLOCKLY_TOOLTIP_LOG_OUTPUT: '输出日志信息，支持 info/error/warn/debug',
  BLOCKLY_TOOLTIP_LOG_INFO: '输出普通级别日志 (log.info)',
  BLOCKLY_TOOLTIP_LOG_WARN: '输出警告级别日志 (log.warn)',
  BLOCKLY_TOOLTIP_LOG_ERROR: '输出错误级别日志 (log.error)',
  BLOCKLY_TOOLTIP_LOG_DEBUG: '输出调试级别日志 (log.debug)',
  BLOCKLY_TOOLTIP_MESSAGE_SEND_GROUP: '发送群消息 (message.send_group)',
  BLOCKLY_TOOLTIP_MESSAGE_SEND_PRIVATE: '发送私聊消息 (message.send_private)',
  BLOCKLY_TOOLTIP_MESSAGE_REPLY: '根据事件自动回复群聊或私聊',
  BLOCKLY_TOOLTIP_MESSAGE_GET_TYPE: '获取消息类型，返回 group 或 private',
  BLOCKLY_TOOLTIP_MESSAGE_GET_PLAIN_TEXT: '获取消息纯文本 (msg.get_plain_text)',
  BLOCKLY_TOOLTIP_MESSAGE_CONTAINS_KEYWORD: '检查消息是否包含指定关键词',
  BLOCKLY_TOOLTIP_MESSAGE_IS_AT_BOT: '检查消息是否 @ 了机器人',
  BLOCKLY_TOOLTIP_MESSAGE_GET_SENDER_ID: '获取发送者用户ID',
  BLOCKLY_TOOLTIP_MESSAGE_GET_GROUP_ID: '获取群ID，私聊场景通常为空或0',
  BLOCKLY_TOOLTIP_MESSAGE_IS_GROUP_MESSAGE: '判断事件是否为群消息（msg.get_type(event) == group）',
  BLOCKLY_TOOLTIP_MESSAGE_IS_PRIVATE_MESSAGE: '判断事件是否为私聊消息（msg.get_type(event) == private）',
  BLOCKLY_TOOLTIP_MESSAGE_SEND_PRIVATE_RESULT: '发送私聊消息并分支处理成功/失败',
  BLOCKLY_TOOLTIP_MESSAGE_SEND_GROUP_RESULT: '发送群消息并分支处理成功/失败',
  BLOCKLY_TOOLTIP_EVENT_ON_MESSAGE: '注册 on_message 事件处理器',
  BLOCKLY_TOOLTIP_EVENT_ON_NOTICE: '注册 on_notice 事件处理器',
  BLOCKLY_TOOLTIP_EVENT_ON_REQUEST: '注册 on_request 事件处理器',
  BLOCKLY_TOOLTIP_EVENT_ON_INIT: '插件启动后立即执行一次',
  BLOCKLY_TOOLTIP_EVENT_ON_DESTROY: '插件停止或卸载前执行一次',
  BLOCKLY_TOOLTIP_EVENT_GET_CURRENT: '获取当前处理中的事件对象',
  BLOCKLY_TOOLTIP_STORAGE_SET: '写入键值数据到插件存储',
  BLOCKLY_TOOLTIP_STORAGE_GET: '读取键值数据，支持默认值',
  BLOCKLY_TOOLTIP_TEXT_CONCAT: '连接两个文本字符串',
  BLOCKLY_TOOLTIP_TEXT_TEMPLATE: '文本模板表达式',
  BLOCKLY_TOOLTIP_LOGIC_IF_ELSE: '条件分支语句',
  BLOCKLY_TOOLTIP_API_CALL_WITH_RESULT: '调用API并分支处理成功/失败',
};

export function initChineseLocale(): void {
  Blockly.setLocale(ZhHans as unknown as Record<string, string>);
  Object.entries(CUSTOM_MSG).forEach(([key, value]) => {
    Blockly.Msg[key] = value;
  });
}

